import mongoose from "mongoose";

const refundSchema = new mongoose.Schema({
  order: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "Order",
    required: true, // References the order containing the product
  },
  product: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "Product",
    required: true, // References the specific product being refunded
  },
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "User",
    required: true, // References the user requesting the refund
  },
  refundId: {
    type: String,
    required: true, // Unique identifier for the refund (e.g., generated by payment gateway or internal)
    unique: true
  },
  amount: {
    type: Number,
    required: true, // Amount to be refunded for the product
    min: 0
  },
  reason: {
    type: String,
    required: true, // Reason for refund (e.g., "Defective product", "Customer request")
  },
  status: {
    type: String,
    enum: ["Requested", "Processing", "Approved", "Rejected", "Completed"],
    default: "Requested",
  },
  requestedAt: {
    type: Date,
    default: Date.now,
  },
  processedAt: {
    type: Date,
    default: null, // Updated when refund is processed
  },
  paymentRefundId: {
    type: String,
    default: null, // Payment gateway refund ID (e.g., Razorpay refund ID)
  },
}, { timestamps: true });

// Index to improve query performance for refund lookups
refundSchema.index({ order: 1, product: 1, refundId: 1 });

const Refund = mongoose.model("Refund", refundSchema);

export default Refund;